In [1]:
import pandas as pd

combined_df = pd.read_csv("dataset_preprocessed.csv")

In [2]:
combined_df.groupby("AI_flag")["resolution_time_hours"].describe()

,count,mean,std,min,25%,50%,75%,max
AI_flag,,,,,,,,
0,4561.0,68.233450,125.151362,0.500000,2.429722,16.570278,67.979722,719.918056
1,4232.0,72.173423,128.129693,0.501111,2.690139,14.062778,82.172153,719.380000

In [3]:
from scipy.stats import mannwhitneyu

ai = combined_df[combined_df["AI_flag"] == 1]["resolution_time_hours"]
human = combined_df[combined_df["AI_flag"] == 0]["resolution_time_hours"]

mannwhitneyu(ai, human)

MannwhitneyuResult(statistic=np.float64(9895847.0), pvalue=np.float64(0.039586388719000026))

In [4]:
median_ai = ai.median()
median_human = human.median()

effect = (median_human - median_ai) / median_human * 100

effect

15.132516386434894

In [5]:
h3_table = combined_df.groupby(["pr_type", "AI_flag"])["resolution_time_hours"].median().unstack()

h3_table["difference"] = h3_table[1] - h3_table[0]
h3_table["effect_%"] = (h3_table[0] - h3_table[1]) / h3_table[0] * 100

h3_table = h3_table.rename(columns={
    0: "human_median",
    1: "ai_median"
}).round(2)

h3_table

AI_flag        human_median  ai_median  difference  effect_%
pr_type
bug_fix               18.01      21.64        3.63    -20.14
documentation         18.00       6.11      -11.89     66.04
feature               18.17       7.89      -10.28     56.58
maintenance            4.77       3.04       -1.73     36.19
other                  8.44      14.40        5.96    -70.69
refactor               6.98       1.53       -5.45     78.09
test                  10.14       5.91       -4.24     41.78

In [6]:
from scipy.stats import mannwhitneyu

results = {}

for pr_type in combined_df["pr_type"].unique():
    subset = combined_df[combined_df["pr_type"] == pr_type]
    
    ai = subset[subset["AI_flag"] == 1]["resolution_time_hours"]
    human = subset[subset["AI_flag"] == 0]["resolution_time_hours"]
    
    if len(ai) > 10 and len(human) > 10:
        stat, p = mannwhitneyu(ai, human)
        results[pr_type] = p

results

{'feature': np.float64(0.00025041492394275517),
 'bug_fix': np.float64(2.431306539631361e-08),
 'other': np.float64(0.0985698202076867),
 'refactor': np.float64(0.2165601639959176),
 'documentation': np.float64(0.007189695931944057),
 'maintenance': np.float64(0.8006245518287685),
 'test': np.float64(0.15373792470570521)}

In [7]:
p_values = pd.Series(results, name="p_value")

final_h3 = h3_table.merge(p_values, left_index=True, right_index=True)

final_h3

               human_median  ai_median  difference  effect_%       p_value
bug_fix               18.01      21.64        3.63    -20.14  2.431307e-08
documentation         18.00       6.11      -11.89     66.04  7.189696e-03
feature               18.17       7.89      -10.28     56.58  2.504149e-04
maintenance            4.77       3.04       -1.73     36.19  8.006246e-01
other                  8.44      14.40        5.96    -70.69  9.856982e-02
refactor               6.98       1.53       -5.45     78.09  2.165602e-01
test                  10.14       5.91       -4.24     41.78  1.537379e-01

In [8]:
repo_analysis = combined_df.groupby(["repo", "AI_flag"])["resolution_time_hours"].median().unstack()

repo_analysis["difference"] = repo_analysis[1] - repo_analysis[0]

repo_analysis

AI_flag                            0          1  difference
repo
antiwork/gumroad           51.291111  89.850972   38.559861
dotnet/aspnetcore          24.944444   4.139306  -20.805139
featureform/enrichmcp      20.546667  17.491667   -3.055000
glaredb/glaredb             8.592778  17.018889    8.426111
jina-ai/node-deepresearch   9.055139   1.220278   -7.834861
liam-hq/liam               12.873333  25.493056   12.619722
microsoft/testfx            4.375694   5.228889    0.853194
mlflow/mlflow              16.386389  25.258194    8.871806
pdfme/pdfme                19.653333   8.933889  -10.719444
prebid/prebid.js           43.529028  39.969028   -3.560000
promptfoo/promptfoo         6.837222   9.484306    2.647083
yamadashy/repomix          13.456528  12.586944   -0.869583

In [9]:
pd.set_option("display.max_rows", None)

repo_type = combined_df.groupby(
    ["repo", "pr_type", "AI_flag"]
)["resolution_time_hours"].median().unstack()

repo_type["difference"] = repo_type[1] - repo_type[0]
repo_type["effect_%"] = (repo_type[0] - repo_type[1]) / repo_type[0] * 100

repo_type_clean = repo_type.dropna(subset=[0, 1])

repo_type_clean = repo_type_clean.rename(columns={
    0: "human_median",
    1: "ai_median"
}).round(2)

repo_type_clean.reset_index()

AI_flag,repo,pr_type,human_median,ai_median,difference,effect_%
0,antiwork/gumroad,bug_fix,59.54,92.96,33.42,-56.12
1,antiwork/gumroad,documentation,6.50,36.24,29.74,-457.85
2,antiwork/gumroad,feature,44.29,148.56,104.27,-235.45
3,antiwork/gumroad,other,25.10,28.11,3.01,-12.00
4,antiwork/gumroad,refactor,6.53,37.56,31.03,-475.02
5,antiwork/gumroad,test,137.06,98.56,-38.50,28.09
6,dotnet/aspnetcore,bug_fix,28.39,13.78,-14.61,51.46
7,dotnet/aspnetcore,documentation,27.34,19.66,-7.68,28.09
8,dotnet/aspnetcore,feature,69.00,2.93,-66.07,95.76
9,dotnet/aspnetcore,maintenance,19.20,2.39,-16.81,87.56
10,dotnet/aspnetcore,other,10.86,16.30,5.44,-50.07
11,dotnet/aspnetcore,test,13.08,5.84,-7.24,55.38
12,featureform/enrichmcp,bug_fix,14.66,63.29,48.63,-331.75
13,featureform/enrichmcp,feature,9.49,3.31,-6.18,65.08
14,featureform/enrichmcp,refactor,272.00,14.07,-257.93,94.83
15,glaredb/glaredb,bug_fix,11.67,25.71,14.04,-120.25
16,glaredb/glaredb,documentation,9.89,6.75,-3.14,31.73
17,glaredb/glaredb,feature,11.75,0.95,-10.80,91.91
18,glaredb/glaredb,refactor,7.90,0.54,-7.36,93.16
19,jina-ai/node-deepresearch,bug_fix,15.88,3.96,-11.92,75.05
20,jina-ai/node-deepresearch,documentation,1.93,14.31,12.38,-639.76
21,jina-ai/node-deepresearch,feature,1.56,1.08,-0.48,30.59
22,liam-hq/liam,bug_fix,14.87,25.49,10.62,-71.45
23,liam-hq/liam,feature,6.59,21.29,14.70,-222.86
24,liam-hq/liam,maintenance,9.58,50.80,41.22,-430.38
25,microsoft/testfx,bug_fix,4.59,3.82,-0.77,16.73
26,microsoft/testfx,documentation,38.93,2.42,-36.50,93.78
27,microsoft/testfx,feature,2.53,1.93,-0.59,23.51
28,microsoft/testfx,maintenance,3.60,5.52,1.92,-53.46
29,microsoft/testfx,other,8.39,0.93,-7.46,88.94
30,microsoft/testfx,refactor,3.37,1.23,-2.13,63.37
31,microsoft/testfx,test,9.48,5.62,-3.86,40.74
32,mlflow/mlflow,bug_fix,17.54,26.90,9.35,-53.31
33,mlflow/mlflow,feature,34.12,9.50,-24.62,72.15
34,mlflow/mlflow,maintenance,1.48,1.26,-0.22,14.84
35,mlflow/mlflow,other,1.63,2.48,0.84,-51.47
36,pdfme/pdfme,bug_fix,21.93,9.49,-12.45,56.75
37,pdfme/pdfme,documentation,15.59,7.67,-7.92,50.81
38,pdfme/pdfme,feature,28.64,7.83,-20.81,72.67
39,pdfme/pdfme,other,10.77,57.67,46.91,-435.71
40,prebid/prebid.js,bug_fix,35.76,35.72,-0.05,0.13
41,prebid/prebid.js,documentation,107.96,17.88,-90.08,83.44
42,prebid/prebid.js,feature,48.54,79.59,31.05,-63.98
43,prebid/prebid.js,refactor,69.80,1.03,-68.77,98.52
44,promptfoo/promptfoo,bug_fix,7.31,8.64,1.33,-18.24
45,promptfoo/promptfoo,documentation,8.93,13.26,4.33,-48.43
46,promptfoo/promptfoo,feature,9.44,14.10,4.66,-49.39
47,promptfoo/promptfoo,maintenance,4.65,1.68,-2.96,63.80
48,promptfoo/promptfoo,other,4.26,5.27,1.01,-23.74
49,promptfoo/promptfoo,refactor,4.89,11.98,7.08,-144.76
50,promptfoo/promptfoo,test,9.25,5.62,-3.63,39.24
51,yamadashy/repomix,bug_fix,16.85,13.30,-3.55,21.08
52,yamadashy/repomix,documentation,2.52,1.85,-0.67,26.72
53,yamadashy/repomix,feature,12.27,7.39,-4.88,39.76
54,yamadashy/repomix,refactor,15.11,1.48,-13.63,90.17

In [10]:
combined_df["normalized_time"] = combined_df.groupby("repo")["resolution_time_hours"].transform(
    lambda x: x / x.median()
)

combined_df.groupby(["pr_type", "AI_flag"])["normalized_time"].median().unstack()

AI_flag               0         1
pr_type
bug_fix        1.050330  1.188876
documentation  1.212403  0.569220
feature        1.070338  0.673448
maintenance    0.362518  0.316682
other          0.679285  0.402043
refactor       0.683459  0.193324
test           0.899021  1.120727